Document: canaima-fondo-institucional
Title: Debian canaima-fondo-institucional Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-fondo-institucional is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-fondo-institucional/canaima-fondo-institucional.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-fondo-institucional/canaima-fondo-institucional.ps.gz

Format: text
Files: /usr/share/doc/canaima-fondo-institucional/canaima-fondo-institucional.text.gz

Format: HTML
Index: /usr/share/doc/canaima-fondo-institucional/html/index.html
Files: /usr/share/doc/canaima-fondo-institucional/html/*.html
